const S={mode:'free',targetKm:5,targetMin:30,running:false,paused:false,start:null,pauseAt:null,pausedMs:0,timer:null,watch:null,last:null,meters:0,points:[],recent:[],laps:[],nextLap:1000,lastLapMs:0,map:null,line:null,marker:null,follow:true,resultMap:null};
const $=id=>document.getElementById(id);
const E={setup:$('setup'),run:$('run'),distanceSet:$('distanceSet'),timeSet:$('timeSet'),dValue:$('dValue'),tValue:$('tValue'),distance:$('distance'),timer:$('timer'),currentPace:$('currentPace'),avgPace:$('avgPace'),gpsStatus:$('gpsStatus'),accuracy:$('accuracy'),progressLabel:$('progressLabel'),progressText:$('progressText'),bar:$('bar'),liveLaps:$('liveLaps'),lapCount:$('lapCount'),resultDialog:$('resultDialog'),rDistance:$('rDistance'),rTime:$('rTime'),rPace:$('rPace'),resultLaps:$('resultLaps'),historyDialog:$('historyDialog'),historyList:$('historyList'),weekKm:$('weekKm'),monthKm:$('monthKm')};

document.querySelectorAll('.tab').forEach(b=>b.onclick=()=>{document.querySelectorAll('.tab').forEach(x=>x.classList.remove('active'));b.classList.add('active');S.mode=b.dataset.mode;E.distanceSet.classList.toggle('hidden',S.mode!=='distance');E.timeSet.classList.toggle('hidden',S.mode!=='time');});
$('dMinus').onclick=()=>{S.targetKm=Math.max(.1,+(S.targetKm-.1).toFixed(1));E.dValue.textContent=S.targetKm.toFixed(1)};
$('dPlus').onclick=()=>{S.targetKm=Math.min(100,+(S.targetKm+.1).toFixed(1));E.dValue.textContent=S.targetKm.toFixed(1)};
$('tMinus').onclick=()=>{S.targetMin=Math.max(1,S.targetMin-1);E.tValue.textContent=S.targetMin};
$('tPlus').onclick=()=>{S.targetMin=Math.min(600,S.targetMin+1);E.tValue.textContent=S.targetMin};
$('startBtn').onclick=startRun;$('pauseBtn').onclick=togglePause;$('stopBtn').onclick=()=>finish(false);
$('recenter').onclick=()=>{S.follow=true;if(S.last&&S.map)S.map.setView([S.last.lat,S.last.lng],Math.max(S.map.getZoom(),16))};
$('closeResult').onclick=()=>{E.resultDialog.close();resetUI();updateSummary()};
$('historyBtn').onclick=()=>{renderHistory();E.historyDialog.showModal()};
$('closeHistory').onclick=()=>E.historyDialog.close();
$('clearHistory').onclick=()=>{if(confirm('すべてのランニング履歴を削除しますか？')){localStorage.removeItem('runningPwaRuns');renderHistory();updateSummary()}};

function startRun(){if(!navigator.geolocation){alert('位置情報を利用できません。');return}if(typeof L==='undefined'){alert('地図を読み込めませんでした。通信状態を確認してください。');return}resetState();S.running=true;S.start=Date.now();E.setup.classList.add('hidden');E.run.classList.remove('hidden');E.gpsStatus.textContent='GPS取得中';initRunMap();S.timer=setInterval(tick,250);S.watch=navigator.geolocation.watchPosition(onPos,onGeoErr,{enableHighAccuracy:true,maximumAge:1000,timeout:10000});updateProgress()}
function initRunMap(){if(S.map)S.map.remove();S.map=L.map('runMap').setView([35.6812,139.7671],14);L.tileLayer('https://tile.openstreetmap.org/{z}/{x}/{y}.png',{maxZoom:19,attribution:'&copy; OpenStreetMap contributors'}).addTo(S.map);S.line=L.polyline([],{weight:5,opacity:.9,lineJoin:'round'}).addTo(S.map);S.map.on('dragstart zoomstart',()=>S.follow=false);setTimeout(()=>S.map.invalidateSize(),100)}
function togglePause(){if(!S.running)return;S.paused=!S.paused;if(S.paused){S.pauseAt=Date.now();$('pauseBtn').textContent='再開';E.gpsStatus.textContent='一時停止中'}else{S.pausedMs+=Date.now()-S.pauseAt;S.pauseAt=null;S.last=null;S.recent=[];$('pauseBtn').textContent='一時停止';E.gpsStatus.textContent='計測中'}}
function onPos(p){if(!S.running||S.paused)return;const c=p.coords,pt={lat:c.latitude,lng:c.longitude,accuracy:c.accuracy,t:p.timestamp||Date.now()};E.accuracy.textContent=`精度 ${Math.round(pt.accuracy)} m`;if(pt.accuracy>40){E.gpsStatus.textContent='GPS精度低';return}if(S.last){const d=haversine(S.last,pt),dt=Math.max((pt.t-S.last.t)/1000,.1),v=d/dt;if(d>=3&&v<=9.72){S.meters+=d;S.points.push(pt);S.recent.push(pt);S.recent=S.recent.filter(x=>pt.t-x.t<=30000);updateRoute(pt);detectLaps()}}else{S.points.push(pt);S.recent=[pt];updateRoute(pt)}S.last=pt;E.gpsStatus.textContent='計測中';updateMetrics();updateProgress();checkGoal()}
function updateRoute(pt){if(!S.map||!S.line)return;const ll=[pt.lat,pt.lng];S.line.addLatLng(ll);if(!S.marker)S.marker=L.circleMarker(ll,{radius:7,weight:3,fillOpacity:1}).addTo(S.map);else S.marker.setLatLng(ll);if(S.follow)S.map.setView(ll,Math.max(S.map.getZoom(),16),{animate:true})}
function detectLaps(){while(S.meters>=S.nextLap){const e=elapsed(),lapMs=e-S.lastLapMs;S.laps.push({n:S.laps.length+1,ms:Math.round(lapMs),pace:Math.round(lapMs/1000)});S.lastLapMs=e;S.nextLap+=1000;renderLiveLaps()}}
function renderLiveLaps(){E.lapCount.textContent=S.laps.length;E.liveLaps.innerHTML=S.laps.length?[...S.laps].reverse().map(l=>`<div class="lapRow"><span>${l.n} km</span><b>${shortTime(l.ms)}</b><span>${pace(l.pace)}/km</span></div>`).join(''):'<p>1 km通過後に表示されます。</p>'}
function onGeoErr(e){E.gpsStatus.textContent='GPSエラー';const m={1:'位置情報が許可されていません。',2:'現在地を取得できません。',3:'位置情報の取得がタイムアウトしました。'};alert(m[e.code]||'位置情報エラーが発生しました。')}
function tick(){if(!S.running)return;updateMetrics();updateProgress();checkGoal()}
function elapsed(){if(!S.start)return 0;const now=Date.now(),cur=S.paused&&S.pauseAt?now-S.pauseAt:0;return Math.max(0,now-S.start-S.pausedMs-cur)}
function updateMetrics(){const ms=elapsed(),sec=ms/1000,km=S.meters/1000;E.distance.textContent=km.toFixed(2);E.timer.textContent=duration(ms);if(km>.03&&sec>10)E.avgPace.textContent=pace(sec/km);const cp=recentPace();E.currentPace.textContent=cp?pace(cp):'--\'--"'}
function recentPace(){if(S.recent.length<2)return null;let d=0;for(let i=1;i<S.recent.length;i++)d+=haversine(S.recent[i-1],S.recent[i]);const sec=(S.recent.at(-1).t-S.recent[0].t)/1000;if(d<20||sec<5)return null;const v=d/sec;return v<.5?null:1000/v}
function updateProgress(){const km=S.meters/1000,min=elapsed()/60000;if(S.mode==='distance'){const p=Math.min(100,km/S.targetKm*100);E.progressLabel.textContent=`目標 ${S.targetKm.toFixed(1)} km`;E.progressText.textContent=`${p.toFixed(0)}%`;E.bar.style.width=`${p}%`}else if(S.mode==='time'){const p=Math.min(100,min/S.targetMin*100);E.progressLabel.textContent=`目標 ${S.targetMin}分`;E.progressText.textContent=`${p.toFixed(0)}%`;E.bar.style.width=`${p}%`}else{E.progressLabel.textContent='フリーラン';E.progressText.textContent='--';E.bar.style.width='0%'}}
function checkGoal(){if(!S.running||S.paused)return;const km=S.meters/1000,min=elapsed()/60000;if(S.mode==='distance'&&km>=S.targetKm)finish(true);if(S.mode==='time'&&min>=S.targetMin)finish(true)}
function finish(goal){if(!S.running)return;const ms=elapsed();S.running=false;if(S.timer)clearInterval(S.timer);if(S.watch!==null)navigator.geolocation.clearWatch(S.watch);const km=S.meters/1000,avg=km>.03?(ms/1000)/km:null,partial=makePartial(ms),record={id:crypto.randomUUID?crypto.randomUUID():String(Date.now()),date:new Date().toISOString(),distanceKm:+km.toFixed(3),durationMs:Math.round(ms),averagePaceSec:avg?Math.round(avg):null,mode:S.mode,goal,laps:S.laps.map(x=>({...x})),partial,route:thinRoute(S.points,900)};saveRun(record);E.rDistance.textContent=`${km.toFixed(2)} km`;E.rTime.textContent=duration(ms);E.rPace.textContent=avg?`${pace(avg)}/km`:'--\'--"/km';renderResultLaps(record);E.resultDialog.showModal();setTimeout(()=>initResultMap(record.route),100)}
function makePartial(ms){const partialM=S.meters-S.laps.length*1000;if(partialM<50)return null;const partMs=ms-S.lastLapMs,dk=partialM/1000;return{distanceKm:+dk.toFixed(3),ms:Math.round(partMs),pace:Math.round((partMs/1000)/dk)}}
function renderResultLaps(r){let rows=r.laps.map(l=>`<div class="lapRow"><span>${l.n} km</span><b>${shortTime(l.ms)}</b><span>${pace(l.pace)}/km</span></div>`);if(r.partial)rows.push(`<div class="lapRow"><span>残り ${r.partial.distanceKm.toFixed(2)} km</span><b>${shortTime(r.partial.ms)}</b><span>${pace(r.partial.pace)}/km</span></div>`);E.resultLaps.innerHTML=rows.length?rows.join(''):'<p>1 km未満のためラップはありません。</p>'}
function initResultMap(route){if(S.resultMap)S.resultMap.remove();S.resultMap=L.map('resultMap');L.tileLayer('https://tile.openstreetmap.org/{z}/{x}/{y}.png',{maxZoom:19,attribution:'&copy; OpenStreetMap contributors'}).addTo(S.resultMap);if(!route.length){S.resultMap.setView([35.6812,139.7671],14);return}const ll=route.map(p=>[p.lat,p.lng]),line=L.polyline(ll,{weight:5,opacity:.9}).addTo(S.resultMap);L.circleMarker(ll[0],{radius:6,weight:2,fillOpacity:1}).addTo(S.resultMap).bindTooltip('START');if(ll.length>1)L.circleMarker(ll.at(-1),{radius:6,weight:2,fillOpacity:1}).addTo(S.resultMap).bindTooltip('FINISH');S.resultMap.fitBounds(line.getBounds(),{padding:[24,24],maxZoom:17});S.resultMap.invalidateSize()}
function thinRoute(points,max=900){const a=points.map(p=>({lat:+p.lat.toFixed(6),lng:+p.lng.toFixed(6)}));if(a.length<=max)return a;const step=Math.ceil(a.length/max),out=a.filter((_,i)=>i%step===0),last=a.at(-1);if(out.at(-1).lat!==last.lat||out.at(-1).lng!==last.lng)out.push(last);return out}
function resetState(){if(S.timer)clearInterval(S.timer);if(S.watch!==null)navigator.geolocation.clearWatch(S.watch);Object.assign(S,{running:false,paused:false,start:null,pauseAt:null,pausedMs:0,timer:null,watch:null,last:null,meters:0,points:[],recent:[],laps:[],nextLap:1000,lastLapMs:0,line:null,marker:null,follow:true})}
function resetUI(){resetState();if(S.map){S.map.remove();S.map=null}if(S.resultMap){S.resultMap.remove();S.resultMap=null}E.setup.classList.remove('hidden');E.run.classList.add('hidden');$('pauseBtn').textContent='一時停止';E.distance.textContent='0.00';E.timer.textContent='00:00:00';E.currentPace.textContent='--\'--"';E.avgPace.textContent='--\'--"';E.bar.style.width='0%';E.accuracy.textContent='精度 -- m';E.gpsStatus.textContent='GPS準備中';E.lapCount.textContent='0';E.liveLaps.innerHTML='<p>1 km通過後に表示されます。</p>'}
function saveRun(r){const a=getRuns();a.unshift(r);localStorage.setItem('runningPwaRuns',JSON.stringify(a.slice(0,100)))}
function getRuns(){try{return JSON.parse(localStorage.getItem('runningPwaRuns')||'[]')}catch{return[]}}
function renderHistory(){const a=getRuns();if(!a.length){E.historyList.innerHTML='<p>まだ記録がありません。</p>';return}E.historyList.innerHTML=a.map(r=>{const d=new Intl.DateTimeFormat('ja-JP',{year:'numeric',month:'2-digit',day:'2-digit',hour:'2-digit',minute:'2-digit'}).format(new Date(r.date));return`<article class="historyItem"><h3>${d}</h3><div class="historyMeta"><span>${Number(r.distanceKm||0).toFixed(2)} km</span><span>${duration(r.durationMs||0)}</span><span>${r.averagePaceSec?pace(r.averagePaceSec)+'/km':'--'}</span></div></article>`}).join('')}
function updateSummary(){const a=getRuns(),now=new Date(),w=new Date(now),day=(now.getDay()+6)%7;w.setHours(0,0,0,0);w.setDate(now.getDate()-day);const m=new Date(now.getFullYear(),now.getMonth(),1),wk=a.filter(r=>new Date(r.date)>=w).reduce((s,r)=>s+Number(r.distanceKm||0),0),mo=a.filter(r=>new Date(r.date)>=m).reduce((s,r)=>s+Number(r.distanceKm||0),0);E.weekKm.textContent=`${wk.toFixed(1)} km`;E.monthKm.textContent=`${mo.toFixed(1)} km`}
function duration(ms){const s=Math.floor(ms/1000),h=Math.floor(s/3600),m=Math.floor(s%3600/60),ss=s%60;return[h,m,ss].map(x=>String(x).padStart(2,'0')).join(':')}
function shortTime(ms){const s=Math.round(ms/1000),m=Math.floor(s/60),ss=s%60;return`${m}:${String(ss).padStart(2,'0')}`}
function pace(sec){if(!Number.isFinite(sec)||sec<=0||sec>3600)return'--\'--"';let m=Math.floor(sec/60),s=Math.round(sec%60);if(s===60){m++;s=0}return`${m}'${String(s).padStart(2,'0')}"`}
function haversine(a,b){const R=6371000,rad=x=>x*Math.PI/180,dLat=rad(b.lat-a.lat),dLon=rad(b.lng-a.lng),la1=rad(a.lat),la2=rad(b.lat),h=Math.sin(dLat/2)**2+Math.cos(la1)*Math.cos(la2)*Math.sin(dLon/2)**2;return 2*R*Math.asin(Math.sqrt(h))}
if('serviceWorker'in navigator)window.addEventListener('load',()=>navigator.serviceWorker.register('service-worker.js').catch(()=>{}));
updateSummary();
